apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-avangelsin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AvangelsTech/avangelsin.git
    targetRevision: HEAD
    path: avangelsin-deployed-yaml-files
  destination:
    server: https://kubernetes.default.svc
    namespace: avangelsin

  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
