apiVersion: v1
kind: PersistentVolume
metadata:
  name: avangelsinwp-pv
  namespace: avangelsin
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/efs/atpl-worker-data-files/avangelsin/html"
